### ISSUE TITLE
Not a bug: But a question

### ISSUE THREAD

**Issue by MikeMannox** [iMicknl/ha-nest-protect#396]
### Description

How does Nest protect report the states?
If I look in _Developer tools -> States_ the state is "off"
```binary_sensor.nest_protect_kitchen_smoke_status``` 

<img width="900" alt="nest_protect_off" src="https://github.com/user-attachments/assets/71d79c8f-7849-4d31-b41a-3cd7cfe87eed" />

yet the sensors seem to report a state type:

States to select from: 
<img width="404" alt="nest_protect_states" src="https://github.com/user-attachments/assets/959b876c-2780-449c-97c7-06be962345bb" />

I am trying to make a new card in Sections view but the states don't seem to correspond to ```binary_sensor.nest_protect_kitchen_smoke_status``` 

```yaml
type: grid
cards:
  - type: conditional
    conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Clear
    card:
      camera_view: auto
      type: picture-entity
      entity: binary_sensor.nest_protect_kitchen_smoke_status
      image: /local/nest/nest-protect-green.png
      name: Clear
      show_state: false
      show_name: false
  - type: conditional
    conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Detected
    card:
      camera_view: auto
      type: picture-entity
      entity: binary_sensor.nest_protect_kitchen_smoke_status
      image: /local/nest/nest-protect-red.png
      name: Detected
      show_state: false
      show_name: false
  - type: conditional
    conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Unavailable
    card:
      type: picture-entity
      entity: binary_sensor.nest_protect_kitchen_smoke_status
      image: /local/nest/nest-protect-yellow.png
      name: Unavailable
      show_state: false
      show_name: false
  - type: conditional
    conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Unknown
    card:
      type: picture-entity
      entity: binary_sensor.nest_protect_kitchen_smoke_status
      image: /local/nest/nest-protect-yellow.png
      name: Unknown
      show_state: false
      show_name: false
  - type: tile
    entity: binary_sensor.nest_protect_kitchen_smoke_status
    grid_options:
      columns: full
  - type: markdown
    content: "status: {{ states('binary_sensor.nest_protect_kitchen_smoke_status') }}"
```

Thanks!

**Comment by jazzyisj** [comment]
Unknown and unavailable are valid states for any entity.  A binary sensor state is always "on" or "off.  If a binary sensor (or sensor) has been given a device class the state may be reported in a more friendly matter in the front end.  For example a binary sensor representing a door will show "Open" and "Closed" in the front end (ui), but the states are really "on" and "off".  In developer tools, -> states you see the states as the back end, or HA sees them.

The sensor you are talking about here has a device class of "smoke" so you see the values "Detected" and "Clear" in the front end.

<img width="894" alt="image" src="https://github.com/user-attachments/assets/e1993092-a8e3-44c8-8a93-86f5493e55fb" />

https://www.home-assistant.io/integrations/binary_sensor/#device-class

**Comment by MikeMannox** [comment]
Thanks for the explanation @jazzyisj, although I didn't find it very clear unfortunately.

@jazzyisj wrote:
> In Developer Tools -> States you see the states as the back end, or HA sees them.

Yes, I know Home Assistant "sees them" the state it shows is either "on" or "off"

As in the docs:
![smokey](https://github.com/user-attachments/assets/48d021a3-8f5d-41ad-bd5b-0b01ae4c7dc5)

However, for the the `conditional` card I have in my [question](https://github.com/iMicknl/ha-nest-protect/issues/396#issue-2767576405) what we put?

```yaml
conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Clear # for example clear should be lowercase or off?
        [omitted]
conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Detected # for example detected should be lowercase or on?
conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Unavailable # for example unavailable should be lowercase or what?
conditions:
      - entity: binary_sensor.nest_protect_kitchen_smoke_status
        state: Unknown # for example unknown should be lowercase or what?
```        

Not trying to be awkward, I am trying to understand, and to do so I need to ask questions.

Thank you,

Mike
