### ISSUE TITLE
[TEMP FIX] WAN Connectivity Issues  |  [FEATURE REQUEST] Connectivity Sensor

### ISSUE THREAD

**Issue by jazzyisj** [iMicknl/ha-nest-protect#398]
### Description

This sensor and automations are meant to be a temporary solution to the WAN disconnection issues that are being discussed here https://github.com/iMicknl/ha-nest-protect/issues/63, here https://github.com/iMicknl/ha-nest-protect/issues/256, and here https://github.com/iMicknl/ha-nest-protect/issues/385.

Ultimately I think the solution is going to be for the integration to provide some sort of status sensor that reliably indicates if is receiving data regularly/properly from Nest, regardless of the reason.  Having that data point, the sensors should be able to be cleared when the connection is offline and refreshed when it comes back online similar to how the WAN reset automation below does it.  Most cloud integrations do this, the entities are unavailable if the API can't contact the server.  I understand Nest Protect more waits for signals than polls for them, but there should still be a way to test connectivity no?

So with this automation here we're kind of using a hammer to kill a fly by reloading the integration when the WAN status changes, and this only works if the problem is the WAN going offline.  The automation doesn't work if say the Nest server goes down which a robust integration status sensor should.

To use this automation you must have a WAN connected sensor.  Easiest way is to create a ping sensor for 1.1.1.1 (Cloudflare).
Obviously you need to change any entity_id's to suitable ones from your configuration.

In testing the WAN Reset automation, the instant the WAN goes offline all the Nest Protect sensors become unavailable, as they should.  The reverse was also true, the integration reloads instantly when the WAN comes back online.

I should also note that I also tested the sensors coming back online on their own by disabling both these automations and forcing the sensors to unavailable by reloading the config manually while the WAN was disconnected.  Within a minute, the sensors were back online with no outside help after the WAN was back online.  So I'm not suffering from the unavailable sensor issues after a WAN disconnect that some are.  In my own config, I've left the "on" state out of the WAN Reset automation because the integration is taking care of it.  But for those where it's not, this automation be an acceptable workaround.

I'm interested to know if everyone else has the same experience.

```
automation:
###############################################################################
## Nest Protect WAN Reset
## This automation reloads the Nest Protect integration when the WAN
## goes offline to clear the sensor values and then reloads it again when
## the WAN comes back online to reset and refresh the sensor values.
###############################################################################
  - id: nest_protect_wan_reset
    alias: "Nest Protect WAN Reset"
    description: "Reset next protect when WAN status changes."
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.wan
        to:
          - "on"
          - "off"
        not_from:
          - unknown
          - unavailable
    actions:
      - action: homeassistant.reload_config_entry
        target:
          entity_id: binary_sensor.nest_protect_upstairs_smoke_status
```

I also put together a "heartbeat" or "watchdog" automation and sensor.  It works very well in theory but as it turns out in reality doesn't work very well for this particular integration because the sensors still appear to get updated even when they are not.

To test it I disabled the WAN reset automation above and took the batteries out of one of my Protects a few hours before the testing and then disconnected the WAN for a while.  The sensors all still appeared to be working while the WAN was disconnected and the last_reported attribute was updated every 5 minutes as if everything was online normally.  Obviously that's an issue.  I understand the integration can only report the values the app reports but protect didn't appear to go offline at all for the couple of hours the WAN was off.  They definitely weren't communicating with Nest!

The template sensor below does properly indicate if the integration is offline when the WAN is offline when used with the WAN Reset automation but I can't really tell if it is actually updating the entities otherwise, but it doesn't appear so if my WAN offline and batteries out test is any indication.

```
automation:
###############################################################################
## Nest Protect Update
## This automation updates entities from the Next Protect integration every
## 5 minutes as a heartbeat and update the last_reported attribute so we can
## determine if the integration is connected or not
###############################################################################
  - id: nest_protect_update
    alias: "Nest Protect Update"
    description: "Update next protect entities."
    triggers:
      - trigger: time_pattern
        minutes: "/5"
    conditions:
      - condition: state
        entity_id:
          - binary_sensor.next_protect_connected
          - binary_sensor.wan
        state: "on"
    actions:
      - action: homeassistant.update_entity
        data:
          entity_id:
            - binary_sensor.nest_protect_upstairs_smoke_status
            - binary_sensor.nest_protect_downstairs_smoke_status

###############################################################################
## Template - Nest Protect Integration Connected
## This template checks the last_reported attribute of Nest Protect entities
## every minute to make sure there has been an update to at least one of the
## sensors in the last 15 minutes to determine if the integration is connected.
###############################################################################
template:
  - trigger:
      - trigger: homeassistant
        event: start

      - trigger: event
        event_type: event_template_reloaded

      - trigger: time_pattern
        minutes: "/1"
    binary_sensor:
      - name: "Nest Protect Integration Connected"
        unique_id: nest_protect_integration_connected
        picture: !secret NEST_PROTECT_ICON
        device_class: connectivity
        state: >
          {%- set threshold = now() - timedelta(minutes=15) %}
          {{ expand(integration_entities('nest_protect'))
              | selectattr('last_reported', 'gt', threshold)
              | list | count > 0 }}

```

### Device (optional)

Topaz-2.7 (Nest Protect - Battery)

### Additional information

Here are some other debugging templates you can put in the developer tools template parser to watch what is happening with the Nest Protect entities.

```
{%- set threshold = now() - timedelta(minutes=15) %}
Are there any entities that have recently reported?
{{ expand(integration_entities('nest_protect'))
    | selectattr('last_updated', 'gt', threshold)
    | list | count > 0 }}

Most recent last_reported time
{%- set lr_times = expand(integration_entities('nest_protect'))
    | map(attribute='last_reported')
    | list %}
{{ as_local(lr_times | max) if lr_times | count > 0 }}

Most recent last_updated time
{% set lu_times = expand(integration_entities('nest_protect'))
    | map(attribute='last_updated')
    | list %}
{{- as_local(lu_times | max) if lu_times | count > 0 }}

Sensors with reported time is less than threshold time
{{ expand(integration_entities('nest_protect'))
    | selectattr('last_reported', 'gt', threshold)
    | map(attribute='entity_id')
    | list }}

Last reported times
{{ expand(integration_entities('nest_protect'))
    | selectattr('last_reported', 'gt', threshold)
    | map(attribute='last_reported')
    | list }}

Sensors with reported times are greater than threshold time
{{ expand(integration_entities('nest_protect'))
    | selectattr('last_reported', 'lt', threshold)
    | map(attribute='entity_id')
    | list }}
Last reported times
{{ expand(integration_entities('nest_protect'))
    | selectattr('last_reported', 'lt', threshold)
    | map(attribute='last_reported')
    | list }}
```
